resources:
  - ../../../base/airQuality

patchesStrategicMerge:
  - deployment.yaml

images:
  - name: ghcr.io/noaa-gsl/mats/development/airQuality
    newTag: development 

configMapGenerator:
  - name: airQuality-config
    files:
      - settings.json # Should mirror the appropriate settings.json file in mats-settings

secretGenerator:
  - name: airQuality-secret
    envs:
      - .env # Should contain mongo_url, root_url, and delay
