apiVersion: v1
kind: Service
metadata:
  name: airQuality
  labels:
    app: airQuality
spec:
  selector:
    app: airQuality
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
